In [2]:
import numpy as np

In [3]:
A = np.ones((3, 4))
B = np.ones((3, 4))
print(f"Shapes are compatible: {A.shape} and {B.shape}")
print("-" * 30)

Shapes are compatible: (3, 4) and (3, 4)
------------------------------


In [4]:
C = np.arange(4)
print(f"Shapes are compatible: {A.shape} and {C.shape}")
print("Broadcasting C (4,) across A (3, 4):")
print(A + C)
print("-" * 30)

Shapes are compatible: (3, 4) and (4,)
Broadcasting C (4,) across A (3, 4):
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
------------------------------


In [6]:
D = np.array([[10], [20], [30]])
print(f"Shapes are compatible: {A.shape} and {D.shape}")
print("Broadcasting D (3, 1) across A (3, 4):")
print(A + D)
print("-" * 30)

Shapes are compatible: (3, 4) and (3, 1)
Broadcasting D (3, 1) across A (3, 4):
[[11. 11. 11. 11.]
 [21. 21. 21. 21.]
 [31. 31. 31. 31.]]
------------------------------


In [7]:
E = np.arange(3)
try:
    print(f"Attempting to broadcast shapes: {A.shape} and {E.shape}")
    print(A + E) # This will raise a ValueError
except ValueError as e:
    print("WOW! The broadcasting rule was violated!")
    print(f"Error: {e}")
    print("NumPy protected us from a silent mistake!")
print("-" * 30)

Attempting to broadcast shapes: (3, 4) and (3,)
WOW! The broadcasting rule was violated!
Error: operands could not be broadcast together with shapes (3,4) (3,) 
NumPy protected us from a silent mistake!
------------------------------


In [8]:
crew_scores = np.array([85, 92, 10, 95, 88])
print(f"Original crew scores before fixing: {crew_scores}")

bad_score_view = crew_scores[2:3]
bad_score_view[0] = 78

print(f"WOW! Scores after fixing the view: {crew_scores}")
print("We accidentally changed the original data!")
print("-" * 30)

Original crew scores before fixing: [85 92 10 95 88]
WOW! Scores after fixing the view: [85 92 78 95 88]
We accidentally changed the original data!
------------------------------


In [10]:
crew_scores = np.array([85, 92, 10, 95, 88]) 
bad_score_copy = crew_scores[2:3].copy() 

bad_score_copy[0] = 78

print("Original scores after fixing the copy "
      f"(it's unchanged!): {crew_scores}")
print("Phew! We used .copy() and protected our original data.")

Original scores after fixing the copy (it's unchanged!): [85 92 10 95 88]
Phew! We used .copy() and protected our original data.
