In [2]:
import numpy as np

In [2]:
expedition_crew_scores = [85, 92, 78, 95, 88]
crew_array = np.array(expedition_crew_scores)
print("1D Array (our single steel beam of crew scores):")
print(crew_array)
print("-" * 30)

1D Array (our single steel beam of crew scores):
[85 92 78 95 88]
------------------------------


In [3]:
treasure_grid_map = [
    [10, 20, 30, 40, 50],  
    [60, 70, 80, 90, 100]   
]
map_array = np.array(treasure_grid_map)
print("2D Array (our treasure grid map - 2 rows, 5 columns):")
print(map_array)
print("-" * 30)

2D Array (our treasure grid map - 2 rows, 5 columns):
[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
------------------------------


In [4]:
multi_layer_scan = np.array([
    [
        [1, 2, 3, 4, 5],    # Layer 0, Row 0
        [6, 7, 8, 9, 10],    # Layer 0, Row 1
        [11, 12, 13, 14, 15]  # Layer 0, Row 2
    ],
    [
        [16, 17, 18, 19, 20], # Layer 1, Row 0
        [21, 22, 23, 24, 25], # Layer 1, Row 1
        [26, 27, 28, 29, 30]  # Layer 1, Row 2
    ]
])
print("3D Array (our multi-layer geological scan - 2x3x5):")
print(multi_layer_scan)
print("-" * 30)

3D Array (our multi-layer geological scan - 2x3x5):
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]
------------------------------


In [7]:
empty_logbook = np.zeros((3, 5)) # A 3x5 grid of zeros
print("Array of Zeros (our empty logbook - 3x5):")
print(empty_logbook)

Array of Zeros (our empty logbook - 3x5):
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
success_template = np.ones((2, 2)) # A 2x2 grid of ones
print("\nArray of Ones (our success template - 2x2):")
print(success_template)


Array of Ones (our success template - 2x2):
[[1. 1.]
 [1. 1.]]


In [10]:
compass_sequence = np.arange(0, 10, 2) 
print("\nArray of a sequence (our compass settings - 0 to 8, step of 2):")
print(compass_sequence)


Array of a sequence (our compass settings - 0 to 8, step of 2):
[0 2 4 6 8]


In [ ]:
waypoints = np.linspace(0, 100, 5) 
print("\nArray of 5 evenly spaced numbers from 0 to 100 (our waypoints):")
print(waypoints)
print("-" * 30)


Array of 5 evenly spaced numbers from 0 to 100 (our waypoints):
[  0.  25.  50.  75. 100.]
------------------------------


In [ ]:
random_interference = np.random.rand(4, 4) 
print("WOW! A random 4x4 array of floats (our atmospheric interference map):")
print(random_interference)

WOW! A random 4x4 array of floats (our atmospheric interference map):
[[0.22688567 0.63236754 0.88475392 0.5536889 ]
 [0.62456872 0.07746396 0.51839472 0.68645189]
 [0.75587239 0.11795298 0.35709916 0.84462773]
 [0.04479623 0.58881663 0.72414227 0.06834841]]


In [13]:
dice_rolls = np.random.randint(1, 7, size=10)
print("\nAnother WOW! 10 random dice rolls (numbers from 1 to 6):")
print(dice_rolls)
print("-" * 30)


Another WOW! 10 random dice rolls (numbers from 1 to 6):
[3 1 2 5 4 4 6 4 4 6]
------------------------------
