In [1]:
import numpy as np

sales_data = np.array([
    [100, 150, 120],  # Electronics sales
    [250, 210, 280]   # Clothing sales
])
print("Our sales grid:")
print(sales_data)
print("-" * 30)

Our sales grid:
[[100 150 120]
 [250 210 280]]
------------------------------


In [ ]:
print(f"Sales for Electronics on Day 2 (positive index):\
      {sales_data[0, 1]}")
print("-" * 30)

Sales for Electronics on Day 2 (positive index): 150
------------------------------


In [ ]:
print(f"Sales for Clothing on the last day (-1 index):\
      {sales_data[1, -1]}")
print("-" * 30)

Sales for Clothing on the last day (-1 index): 280
------------------------------


In [4]:
print("All sales for Electronics:")
print(sales_data[0, :])
print("-" * 30)

All sales for Electronics:
[100 150 120]
------------------------------


In [5]:
print("All sales for Day 3:")
print(sales_data[:, 2])
print("-" * 30)


All sales for Day 3:
[120 280]
------------------------------


In [6]:
high_sales_mask = sales_data > 200
print("The boolean mask (True where sales > 200):")
print(high_sales_mask)
print("\nWOW! All sales greater than 200:")
print(sales_data[high_sales_mask])
print("-" * 30)

The boolean mask (True where sales > 200):
[[False False False]
 [ True  True  True]]

WOW! All sales greater than 200:
[250 210 280]
------------------------------


In [7]:
rows_to_select = [0, 1]   # We want to look at row 0 and row 1
cols_to_select = [0, 2]   # We want to look at column 0 and column 2
teleported_sales = sales_data[rows_to_select, cols_to_select]

# The result is a new array containing the sales values we asked for.
print("WOW! Sales for (Electronics, Day 1) and (Clothing, Day 3):")
print(teleported_sales)
print("-" * 30)

WOW! Sales for (Electronics, Day 1) and (Clothing, Day 3):
[100 280]
------------------------------


In [14]:
############## The Fancy Indexing Teleporter (3D) #############

In [15]:
multi_layer_scan = np.array([
    [
        [1, 2, 3, 4],    # Layer 0, Row 0
        [5, 6, 7, 8],    # Layer 0, Row 1
        [9, 10, 11, 12]  # Layer 0, Row 2
    ],
    [
        [13, 14, 15, 16], # Layer 1, Row 0
        [17, 18, 19, 20], # Layer 1, Row 1
        [21, 22, 23, 24]  # Layer 1, Row 2
    ]
])

In [18]:
layers_to_select = [0, 1]
rows_to_select = [0, 2]
cols_to_select = [1, 3]

teleported_3d_data = multi_layer_scan[layers_to_select, 
                                      rows_to_select, 
                                      cols_to_select]

In [ ]:
print("\nWOW! Teleporting to grab specific values " \
      "from different layers, rows, and columns:")
print(teleported_3d_data)
print("-" * 30)


WOW! Teleporting to grab specific values from different layers, rows, and columns:
[ 2 24]
------------------------------


In [11]:
# This is a view of the first two columns
slice_view = sales_data[:, 0:2] 
# This is a true copy
slice_copy = sales_data[:, 0:2].copy() 

print("Original sales data before modification:")
print(sales_data)


Original sales data before modification:
[[100 150 120]
 [250 210 280]]


In [12]:
slice_view[0, 0] = 9999
print("\nOriginal sales data after modifying the view (it changed!):")
print(sales_data)


Original sales data after modifying the view (it changed!):
[[9999  150  120]
 [ 250  210  280]]


In [13]:
sales_data = np.array([
    [100, 150, 120],
    [250, 210, 280]
])
slice_copy[0, 0] = 9999
print("\nOriginal sales data after modifying the copy (it's unchanged!):")
print(sales_data)
print("-" * 30)


Original sales data after modifying the copy (it's unchanged!):
[[100 150 120]
 [250 210 280]]
------------------------------
