In [1]:
import numpy as np

quarterly_sales = np.array([
    [100, 150, 120, 180], # Product A
    [250, 210, 280, 220], # Product B
    [300, 350, 310, 380]  # Product C
])

In [2]:
sqrt_sales = np.sqrt(quarterly_sales)
print("WOW! Square root of every sales value:")
print(sqrt_sales)
print("-" * 30)

WOW! Square root of every sales value:
[[10.         12.24744871 10.95445115 13.41640786]
 [15.8113883  14.49137675 16.73320053 14.83239697]
 [17.32050808 18.70828693 17.60681686 19.49358869]]
------------------------------


In [6]:
total_sales_overall = np.sum(quarterly_sales)
print("Total sales across all products and quarters:"
       f"{total_sales_overall}")
print("-" * 30)

Total sales across all products and quarters:2850
------------------------------


In [7]:
sales_per_quarter = np.sum(quarterly_sales, axis=0)
print("WOW! Total sales for each quarter (axis=0 reduction):")
print(sales_per_quarter)
print("-" * 30)

WOW! Total sales for each quarter (axis=0 reduction):
[650 710 710 780]
------------------------------


In [8]:
sales_per_product = np.sum(quarterly_sales, axis=1)
print("WOW! Total sales for each product (axis=1 reduction):")
print(sales_per_product)
print("-" * 30)

WOW! Total sales for each product (axis=1 reduction):
[ 550  960 1340]
------------------------------


In [9]:
multi_layer_scan = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])
print("Our 3D geological survey data:")
print(multi_layer_scan)

Our 3D geological survey data:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [11]:
max_value_per_layer = np.max(multi_layer_scan, axis=(1, 2))
print("\nWOW! Maximum value found in each layer "
      "(collapsing rows and columns):")
print(max_value_per_layer)
print("-" * 30)


WOW! Maximum value found in each layer (collapsing rows and columns):
[12 24]
------------------------------
