In [2]:
import numpy as np

crew_scores_start = np.array([85, 92, 78, 95, 88])
crew_scores_end = np.array([88, 95, 75, 98, 90])

In [3]:
score_difference = crew_scores_end - crew_scores_start
print("WOW! The difference in scores (end - start):")
print(score_difference)
print("-" * 30)

WOW! The difference in scores (end - start):
[ 3  3 -3  3  2]
------------------------------


In [4]:
doubled_scores = crew_scores_start * 2
print("WOW! Doubled scores (all at once):")
print(doubled_scores)
print("-" * 30)

WOW! Doubled scores (all at once):
[170 184 156 190 176]
------------------------------


In [5]:
quarterly_sales = np.array([
    [100, 150, 120, 180], # Product A
    [250, 210, 280, 220], # Product B
    [300, 350, 310, 380]  # Product C
])
print("Our original quarterly sales grid:")
print(quarterly_sales)

Our original quarterly sales grid:
[[100 150 120 180]
 [250 210 280 220]
 [300 350 310 380]]


In [6]:
bonus_sales = quarterly_sales + 10
print("\nWOW! All sales with a 10-point bonus (broadcasting a scalar):")
print(bonus_sales)
print("-" * 30)


WOW! All sales with a 10-point bonus (broadcasting a scalar):
[[110 160 130 190]
 [260 220 290 230]
 [310 360 320 390]]
------------------------------


In [9]:
quarterly_bonus = np.array([10, 20, 15, 25])
total_sales = quarterly_sales + quarterly_bonus
print("WOW! Quarterly sales with different bonuses for " \
      "each quarter (broadcasting a 1D array to 2D):")
print(total_sales)
print("-" * 30)

WOW! Quarterly sales with different bonuses for each quarter (broadcasting a 1D array to 2D):
[[110 170 135 205]
 [260 230 295 245]
 [310 370 325 405]]
------------------------------


In [10]:
multi_layer_scan = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])
print("Our 3D geological survey data:")
print(multi_layer_scan)

Our 3D geological survey data:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [11]:
# 100 for Layer 0, 200 for Layer 1
layer_adjustment = np.array([100, 200]) 

In [ ]:
adjusted_scan = multi_layer_scan + \
                layer_adjustment[:, np.newaxis, np.newaxis]

print("\nWOW! Our 3D survey adjusted for each layer "
      "(1D array broadcast to 3D):")
print(adjusted_scan)
print("-" * 30)


WOW! Our 3D survey adjusted for each layer (1D array broadcast to 3D):
[[[101 102 103 104]
  [105 106 107 108]
  [109 110 111 112]]

 [[213 214 215 216]
  [217 218 219 220]
  [221 222 223 224]]]
------------------------------
